---
title: "Indicese interpretation"
output: 
  github_document:
    toc: true
    fig_width: 10.08
    fig_height: 6
  rmarkdown::html_vignette:
    toc: true
    fig_width: 10.08
    fig_height: 6
tags: [r, report]
vignette: >
  \usepackage[utf8]{inputenc}
editor_options: 
  chunk_output_type: console
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  tidy.opts=list(width.cutoff=60),
  tidy=TRUE,
  fig.path = "README-"
)
options(knitr.kable.NA = '',
        digits = 4)
```


## Why?

Many indices used in statistics (indices of fit, model performance or parameter estimate) can be very abstract. A long experience is required to intuitively "*feel*" the meaning of their values. In order to facilitate the understanding of the results they are facing, many scientists use (often implicitly) some set of *rules of thumb*. In order to validate and standardize such interpretation grid, some authors validated and published them in the form of guidelines. One of the most famous interpertation grid was proposed by **Cohen (1988)** for a series of widely used indices, such as the correlation **r** (*r* = .20, small; *r* = .40, moderate and *r* = .60, large) or the standardized difference (Cohen's) ***d***. 

Readers should keep in mind that these thresholds are arbitrary and should be discussed on a case-by-case basis, to avoid their crystalisation as for the infamous ***p* < .05** example. 

`report` implements such sets of rules of thumb for a variety of indices in a flexible and explicit fashion.

## Supported Indices

### Correlation *r*

TODO.