name: Copilot task
description: Request GitHub Copilot assistance for development tasks
title: "[Copilot]: "
labels: ["robot :robot:"]
assignees: Copilot
projects: []
type: Task
body:
  - type: markdown
    attributes:
      value: |
        Request GitHub Copilot assistance for development tasks. This template will automatically assign the issue to @copilot and allow you to specify the appropriate CI environment setup.

  - type: textarea
    id: task-description
    attributes:
      label: Task description
      description: Describe the development task you need assistance with
      placeholder: |
        What do you need help with? Be as specific as possible about:
        - What needs to be implemented/fixed/changed
        - Any relevant context or requirements
        - Expected outcomes
    validations:
      required: true

  - type: dropdown
    id: setup-preference
    attributes:
      label: Copilot setup preference
      description: Choose the CI environment preference for this task
      options:
        - copilot-setup-light
        - copilot-setup-full
      default: 0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        **Setup preference guide:**
        - **copilot-setup-light**: For documentation changes, minor fixes, configuration updates, or tasks that don't require full R environment (saves 5-10 minutes)
        - **copilot-setup-full**: For code changes, new features, function modifications, or tasks requiring complete R development environment

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Provide any additional context, links to related issues, or implementation notes
      placeholder: |
        - Related issues: #XXX
        - Relevant files: path/to/files
        - Implementation notes or constraints
        - Expected behavior

  - type: textarea
    id: example-code
    attributes:
      label: Code example (if applicable)
      description: If relevant, provide example code or show the desired outcome
      placeholder: |
        ```r
        # Example code or desired usage
        ```
      render: r