name: Feature request
description: Suggest a new idea or enhancement for this project
title: "[Feature]: "
labels: ["feature idea :fire:"]
assignees: ["rempsyc"]
projects: []
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details about your idea.

  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Describe your feature idea...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: If you have ideas about how this could be implemented, please share them
      placeholder: How could we implement this? Any technical considerations?

  - type: textarea
    id: example-code
    attributes:
      label: Example usage
      description: If helpful, show how you envision this feature being used
      placeholder: |
        ```r
        library(report)
        # Example of how the new feature might work
        ```
      render: r


