name: Question
description: Ask a question about the package usage or functionality
title: "[Question]: "
labels: ["question :interrobang:"]
assignees: ["rempsyc"]
projects: []
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! Before asking, please check:

        1. **Documentation**: Visit our [documentation site](https://easystats.github.io/report/)
        2. **Discussions**: Browse [existing discussions](https://github.com/easystats/report/discussions) for similar questions
        3. **Update packages**: Ensure you have the latest version with `easystats::install_latest()`

        Please provide details to help us give you the best answer.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: Describe your question in detail...
    validations:
      required: true
