---
title: "report: Automated Reporting of Results and Statistical Models in R"
tags:
  - R
  - easystats
authors:
- affiliation: 1
  name: Dominique Makowski
  orcid: 0000-0001-5375-9967
- affiliation: 2
  name: Indrajeet Patil
  orcid: 0000-0003-1995-6531
- affiliation: 3
  name: Mattan S. Ben-Shachar
  orcid: 0000-0002-4287-4801
- affiliation: 4
  name: Brenton M. Wiernik^[Brenton Wiernik is currently an independent researcher and Research Scientist at Meta, Demography and Survey Science. The current work was done in an independent capacity.]
  orcid: 0000-0001-9560-6336
- affiliation: 5
  name: Daniel Lüdecke
  orcid: 0000-0002-8895-3206
  
affiliations:
- index: 1
  name: Nanyang Technological University, Singapore
- index: 2
  name: cynkra Analytics GmbH, Germany
- index: 3
  name: Ben-Gurion University of the Negev, Israel
- index: 4
  name: Independent Researcher
- index: 5
  name: University Medical Center Hamburg-Eppendorf, Germany
    
date: "`r Sys.Date()`"
bibliography: paper.bib
output: rticles::joss_article
csl: apa.csl
journal: JOSS
link-citations: yes
---

```{r, warning=FALSE, message=FALSE, echo=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  out.width = "100%",
  dpi = 300,
  comment = "#>",
  message = FALSE,
  warning = FALSE
)

library(report)
set.seed(2016)
```

# Summary

The `{report}` package for the R programming language [@base2021] provides

# Statement of Need

The `{report}` package is part of `{easystats}`, a collection of R packages designed to make statistical analysis easier (@Ben-Shachar2020, @Lüdecke2020parameters, @Lüdecke2020performance, @Lüdecke2021see, @Lüdecke2019, @Makowski2019, @Makowski2020, @Patil2022datawizard). 

# Features

# Licensing and Availability

`{report}` is licensed under the GNU General Public License (v3.0), with all source code openly developed and stored on GitHub (<https://github.com/easystats/report>), along with a corresponding issue tracker for bug reporting and feature enhancements. In the spirit of honest and open science, we encourage requests, tips for fixes, feature updates, as well as general questions and concerns via direct interaction with contributors and developers.

# Acknowledgments

`{report}` is part of the collaborative [*easystats*](https://easystats.github.io/easystats/) ecosystem. Thus, we thank the [members of easystats](https://github.com/orgs/easystats/people) as well as the users.

# References
